spring.application.name=yomu-auth
server.port=8081

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate 
spring.jpa.properties.hibernate.default_schema=auth_mod
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

supabase.url=${SUPABASE_URL}
supabase.anon.key=${SUPABASE_KEY}

spring.jackson.serialization.indent_output=true